// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'DisabledItem': string;
  'Item': string;
  'ItemRemove': string;
  'ItemText': string;
  'MultiChoice': string;
  'SelectAll': string;
  'SelectedOptions': string;
}
const cssExports: CssExports;
export default cssExports;
